// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5fYWSBYAgiGfDOsrL9nqNnyf7ZP_GXeI',
    appId: '1:753596072645:android:7d5d3e5a72fa12f98ca6ac',
    messagingSenderId: '753596072645',
    projectId: 'testwhatsapp2-9a674',
    databaseURL: 'https://testwhatsapp2-9a674.firebaseio.com',
    storageBucket: 'testwhatsapp2-9a674.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLPGw4NZKwBleOnojXBDCCP69bUtBeBRE',
    appId: '1:753596072645:ios:2cd7e82bcb7f385c8ca6ac',
    messagingSenderId: '753596072645',
    projectId: 'testwhatsapp2-9a674',
    databaseURL: 'https://testwhatsapp2-9a674.firebaseio.com',
    storageBucket: 'testwhatsapp2-9a674.appspot.com',
    iosClientId: '753596072645-0m1cvhfebdeqjcvu8ndappensj3rkpd0.apps.googleusercontent.com',
    iosBundleId: 'com.hiennv.testing',
  );
}
